### ISSUE TITLE
Would it be easier to query for google+ images for reviews in the backend, or keep in frontend?

### ISSUE THREAD

**Issue by ncrum** [keerthanakumar/cs373-imdb#55]
My question for this refers to the googleImageService.js and reviews.js on the frontend. Right now it works perfectly fine accessing the google plus api on the frontend. Though I don't know if it would be better to add an image_url field to each review and just do the query when parsing reviews, that way we could just access our own api on the frontend and not have to hit the google+ api every time the review page is loaded. What do you think Zo Hra?

**Comment by fzohra** [comment]
Ideally, we would want to hit the google+ api every time, but in the interest of limited google api requests and reasonably large traffic to our website I think making requests to google+ from the frontend could possibly become an issue later on. We have the reviews themselves stored in the db already so we can just add the image_url to the db as well. I've written the migration script in a way that makes it easy to periodically update our database as well by repulling the jsons from google places (which I can actually improve even more now that I think about it).

I think the reviewService.js and googleImageService.js are still great to keep though because there will be times when a user will request for something that we don't have and if we still have json pull requests left on our token, then we can use these service.js to pull that information for them. I know its a little overkill for the scope of our project, but seeing how you guys already have the framework in place.

So imo yes to adding both the image url and the frontend service requests!

**Comment by ncrum** [comment]
Well the googleImageService is the only one that hits the google plus api for the image url for a user. Assuming we put it in the database, it would be irrelevant. We could always just do that later though.

**Comment by fzohra** [comment]
how would it be irrelevant? It would just be "cached"

**Comment by ncrum** [comment]
Because we would already have the image url for every review in the Review table.

**Comment by ncrum** [comment]
Right now this is how it works:
+ We get reviews via the route /api/places/<place_id>/reviews
+ For each review we get the image_url from Google Plus Api on the frontend

How it will work:
+ We get reviews via the route /api/places/<place_id>/reviews
+ image_url is already there for each review, therefore, googleImageService.js is irrelevant

**Comment by fzohra** [comment]
oohh, I meant reviews for a places not stored in the db. For example, suppose the user wanted to search for 'food' 'sushi' and we don't have any results for 'sushi', then we would use the service js calls to get the places and their corresponding reviews and images. If we decide to just return 'No results' or something, then it's irrelevant.

**Comment by ncrum** [comment]
We only want the user to view data in our domain. No places outside of it. Or else we wouldn't be IMDB like

**Comment by fzohra** [comment]
ok, got it. for some reason I was under the impression we would make real time requests if necessary. if not, then I guess we don't need googleImageService.js or reviewService.js

**Comment by fzohra** [comment]
because we can just store all the necessary urls in the db

**Comment by ncrum** [comment]
We do need reviewService since that hits our backend for the data. googleImageService.js we need until the Review table includes an image_url for the author of the review.

**Comment by fzohra** [comment]
yeah, sorry. just looked at it reviewService.js again and it does hit our backend ^^;
